#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "jlib.h"

#define MESSAGE "AAAAAAAAAABBBBBBBBBBBBBCCCCCCCCCCCCDDDDDDDDDDDDD"
#define ETC "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\	
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\ 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"	


int main()
{
	int msg[1024];
	
	memcpy(msg, MESSAGE, strlen(MESSAGE)+1);
	

	printf("%d, %s\n",sizeof(ETC), msg);

	return 0;
}
